package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78-dev

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/pkg/httpclient"
	"github.com/looplj/axonhub/internal/server/biz"
	"github.com/samber/lo"
)

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, input ent.CreateChannelInput) (*ent.Channel, error) {
	return r.channelService.CreateChannel(ctx, input)
}

// BulkCreateChannels is the resolver for the bulkCreateChannels field.
func (r *mutationResolver) BulkCreateChannels(ctx context.Context, input biz.BulkCreateChannelsInput) ([]*ent.Channel, error) {
	return r.channelService.BulkCreateChannels(ctx, input)
}

// UpdateChannel is the resolver for the updateChannel field.
func (r *mutationResolver) UpdateChannel(ctx context.Context, id objects.GUID, input ent.UpdateChannelInput) (*ent.Channel, error) {
	return r.channelService.UpdateChannel(ctx, id.ID, &input)
}

// UpdateChannelStatus is the resolver for the updateChannelStatus field.
func (r *mutationResolver) UpdateChannelStatus(ctx context.Context, id objects.GUID, status channel.Status) (*ent.Channel, error) {
	return r.channelService.UpdateChannelStatus(ctx, id.ID, status)
}

// DeleteChannel is the resolver for the deleteChannel field.
func (r *mutationResolver) DeleteChannel(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.channelService.DeleteChannel(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// BulkArchiveChannels is the resolver for the bulkArchiveChannels field.
func (r *mutationResolver) BulkArchiveChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkArchiveChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDisableChannels is the resolver for the bulkDisableChannels field.
func (r *mutationResolver) BulkDisableChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkDisableChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnableChannels is the resolver for the bulkEnableChannels field.
func (r *mutationResolver) BulkEnableChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkEnableChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteChannels is the resolver for the bulkDeleteChannels field.
func (r *mutationResolver) BulkDeleteChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkDeleteChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// TestChannel is the resolver for the testChannel field.
func (r *mutationResolver) TestChannel(ctx context.Context, input TestChannelInput) (*TestChannelPayload, error) {
	// Set test source context for test channel requests
	ctx = contexts.WithSource(ctx, request.SourceTest)

	result, err := r.testChannelProcessor.TestChannel(ctx, input.ChannelID, input.ModelID, input.Proxy)
	if err != nil {
		if httpclient.IsNotFoundErr(err) {
			return nil, fmt.Errorf("URL not found, please check if the URL is correct and try again")
		}

		return nil, fmt.Errorf("failed to test channel: %w", err)
	}

	return &TestChannelPayload{
		Latency: result.Latency,
		Success: result.Success,
		Error:   result.Error,
	}, nil
}

// BulkImportChannels is the resolver for the bulkImportChannels field.
func (r *mutationResolver) BulkImportChannels(ctx context.Context, input BulkImportChannelsInput) (*biz.BulkImportChannelsResult, error) {
	result, err := r.channelService.BulkImportChannels(ctx, input.Channels)
	if err != nil {
		return nil, err
	}

	return &biz.BulkImportChannelsResult{
		Success:  result.Success,
		Created:  result.Created,
		Failed:   result.Failed,
		Errors:   result.Errors,
		Channels: result.Channels,
	}, nil
}

// BulkUpdateChannelOrdering is the resolver for the bulkUpdateChannelOrdering field.
func (r *mutationResolver) BulkUpdateChannelOrdering(ctx context.Context, input BulkUpdateChannelOrderingInput) (*BulkUpdateChannelOrderingResult, error) {
	updatedChannels, err := r.channelService.BulkUpdateChannelOrdering(ctx, input.Channels)
	if err != nil {
		return nil, fmt.Errorf("failed to bulk update channel ordering: %w", err)
	}

	return &BulkUpdateChannelOrderingResult{
		Success:  true,
		Updated:  len(updatedChannels),
		Channels: updatedChannels,
	}, nil
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input ent.CreateAPIKeyInput) (*ent.APIKey, error) {
	return r.apiKeyService.CreateAPIKey(ctx, input)
}

// UpdateAPIKey is the resolver for the updateAPIKey field.
func (r *mutationResolver) UpdateAPIKey(ctx context.Context, id objects.GUID, input ent.UpdateAPIKeyInput) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKey(ctx, id.ID, input)
}

// UpdateAPIKeyStatus is the resolver for the updateAPIKeyStatus field.
func (r *mutationResolver) UpdateAPIKeyStatus(ctx context.Context, id objects.GUID, status apikey.Status) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKeyStatus(ctx, id.ID, status)
}

// UpdateAPIKeyProfiles is the resolver for the updateAPIKeyProfiles field.
func (r *mutationResolver) UpdateAPIKeyProfiles(ctx context.Context, id objects.GUID, input objects.APIKeyProfiles) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKeyProfiles(ctx, id.ID, input)
}

// BulkDisableAPIKeys is the resolver for the bulkDisableAPIKeys field.
func (r *mutationResolver) BulkDisableAPIKeys(ctx context.Context, ids []*objects.GUID) (bool, error) {
	apiKeyIDs := objects.IntGuids(ids)

	err := r.apiKeyService.BulkDisableAPIKeys(ctx, apiKeyIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkArchiveAPIKeys is the resolver for the bulkArchiveAPIKeys field.
func (r *mutationResolver) BulkArchiveAPIKeys(ctx context.Context, ids []*objects.GUID) (bool, error) {
	apiKeyIDs := objects.IntGuids(ids)

	err := r.apiKeyService.BulkArchiveAPIKeys(ctx, apiKeyIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	return r.userService.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id objects.GUID, input ent.UpdateUserInput) (*ent.User, error) {
	return r.userService.UpdateUser(ctx, id.ID, input)
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id objects.GUID, status user.Status) (*ent.User, error) {
	return r.userService.UpdateUserStatus(ctx, id.ID, status)
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input ent.CreateRoleInput) (*ent.Role, error) {
	return r.roleService.CreateRole(ctx, input)
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id objects.GUID, input ent.UpdateRoleInput) (*ent.Role, error) {
	return r.roleService.UpdateRole(ctx, id.ID, input)
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id objects.GUID) (bool, error) {
	err := r.roleService.DeleteRole(ctx, id.ID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteRoles is the resolver for the bulkDeleteRoles field.
func (r *mutationResolver) BulkDeleteRoles(ctx context.Context, ids []*objects.GUID) (bool, error) {
	roleIDs := objects.IntGuids(ids)

	err := r.roleService.BulkDeleteRoles(ctx, roleIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input ent.CreateProjectInput) (*ent.Project, error) {
	return r.projectService.CreateProject(ctx, input)
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id objects.GUID, input ent.UpdateProjectInput) (*ent.Project, error) {
	return r.projectService.UpdateProject(ctx, id.ID, input)
}

// UpdateProjectStatus is the resolver for the updateProjectStatus field.
func (r *mutationResolver) UpdateProjectStatus(ctx context.Context, id objects.GUID, status project.Status) (*ent.Project, error) {
	return r.projectService.UpdateProjectStatus(ctx, id.ID, status)
}

// AddUserToProject is the resolver for the addUserToProject field.
func (r *mutationResolver) AddUserToProject(ctx context.Context, input AddUserToProjectInput) (*ent.UserProject, error) {
	roleIDs := objects.IntGuids(input.RoleIDs)
	return r.userService.AddUserToProject(ctx, input.UserID.ID, input.ProjectID.ID, input.IsOwner, input.Scopes, roleIDs)
}

// RemoveUserFromProject is the resolver for the removeUserFromProject field.
func (r *mutationResolver) RemoveUserFromProject(ctx context.Context, input RemoveUserFromProjectInput) (bool, error) {
	err := r.userService.RemoveUserFromProject(ctx, input.UserID.ID, input.ProjectID.ID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// UpdateProjectUser is the resolver for the updateProjectUser field.
func (r *mutationResolver) UpdateProjectUser(ctx context.Context, input UpdateProjectUserInput) (*ent.UserProject, error) {
	addRoleIDs := objects.IntGuids(input.AddRoleIDs)
	removeRoleIDs := objects.IntGuids(input.RemoveRoleIDs)

	return r.userService.UpdateProjectUser(ctx, input.UserID.ID, input.ProjectID.ID, input.Scopes, addRoleIDs, removeRoleIDs)
}

// CreateDataStorage is the resolver for the createDataStorage field.
func (r *mutationResolver) CreateDataStorage(ctx context.Context, input ent.CreateDataStorageInput) (*ent.DataStorage, error) {
	return r.dataStorageService.CreateDataStorage(ctx, &input)
}

// UpdateDataStorage is the resolver for the updateDataStorage field.
func (r *mutationResolver) UpdateDataStorage(ctx context.Context, id objects.GUID, input ent.UpdateDataStorageInput) (*ent.DataStorage, error) {
	return r.dataStorageService.UpdateDataStorage(ctx, id.ID, &input)
}

// FetchModels is the resolver for the fetchModels field.
func (r *queryResolver) FetchModels(ctx context.Context, input biz.FetchModelsInput) (*FetchModelsPayload, error) {
	// Call the model fetcher service
	result, err := r.modelFetcher.FetchModels(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch models: %w", err)
	}

	// Convert result to GraphQL payload
	models := make([]*objects.ModelIdentify, len(result.Models))
	for i := range result.Models {
		models[i] = &result.Models[i]
	}

	return &FetchModelsPayload{
		Models: models,
		Error:  result.Error,
	}, nil
}

// Models is the resolver for the models field.
func (r *queryResolver) Models(ctx context.Context, input ModelsInput) ([]*biz.Model, error) {
	// Convert GraphQL input to biz layer input
	bizInput := biz.ListModelsInput{
		StatusIn:       input.StatusIn,
		IncludeMapping: lo.FromPtrOr(input.IncludeMapping, false),
		IncludePrefix:  lo.FromPtrOr(input.IncludePrefix, false),
	}

	// Call the biz layer method directly
	return r.channelService.ListModels(ctx, bizInput)
}

// AllChannelTags is the resolver for the allChannelTags field.
func (r *queryResolver) AllChannelTags(ctx context.Context) ([]string, error) {
	// Query all channels that are not archived
	channels, err := r.client.Channel.
		Query().
		Select(channel.FieldTags).
		Where(channel.StatusNEQ(channel.StatusArchived)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to query channels: %w", err)
	}

	tags := lo.Reduce(channels, func(acc []string, ch *ent.Channel, _ int) []string {
		return append(acc, ch.Tags...)
	}, []string{})

	return lo.Uniq(tags), nil
}

// CountChannelsByType is the resolver for the countChannelsByType field.
func (r *queryResolver) CountChannelsByType(ctx context.Context, input CountChannelsByTypeInput) ([]*ChannelTypeCount, error) {
	// Query channel types with counts
	var results []struct {
		Type  string `json:"type"`
		Count int    `json:"count"`
	}

	q := r.client.Channel.Query()
	if len(input.StatusIn) > 0 {
		q = q.Where(channel.StatusIn(input.StatusIn...))
	} else {
		q = q.Where(channel.StatusNEQ(channel.StatusArchived))
	}

	err := q.GroupBy(channel.FieldType).
		Aggregate(ent.Count()).Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to query channel type counts: %w", err)
	}

	typeCounts := make([]*ChannelTypeCount, len(results))
	for i, result := range results {
		typeCounts[i] = &ChannelTypeCount{
			Type:  result.Type,
			Count: result.Count,
		}
	}

	return typeCounts, nil
}

// QueryChannels is the resolver for the queryChannels field.
func (r *queryResolver) QueryChannels(ctx context.Context, input biz.QueryChannelsInput) (*ent.ChannelConnection, error) {
	if err := validatePaginationArgs(input.First, input.Last); err != nil {
		return nil, err
	}

	// Call the biz layer method directly
	return r.channelService.QueryChannels(ctx, input)
}

// ItemCount is the resolver for the itemCount field.
func (r *requestMetadataResolver) ItemCount(ctx context.Context, obj *biz.RequestMetadata) (*int, error) {
	panic(fmt.Errorf("not implemented: ItemCount - itemCount"))
}

// InputTokens is the resolver for the inputTokens field.
func (r *requestMetadataResolver) InputTokens(ctx context.Context, obj *biz.RequestMetadata) (*int, error) {
	panic(fmt.Errorf("not implemented: InputTokens - inputTokens"))
}

// OutputTokens is the resolver for the outputTokens field.
func (r *requestMetadataResolver) OutputTokens(ctx context.Context, obj *biz.RequestMetadata) (*int, error) {
	panic(fmt.Errorf("not implemented: OutputTokens - outputTokens"))
}

// TotalTokens is the resolver for the totalTokens field.
func (r *requestMetadataResolver) TotalTokens(ctx context.Context, obj *biz.RequestMetadata) (*int, error) {
	panic(fmt.Errorf("not implemented: TotalTokens - totalTokens"))
}

// CachedTokens is the resolver for the cachedTokens field.
func (r *requestMetadataResolver) CachedTokens(ctx context.Context, obj *biz.RequestMetadata) (*int, error) {
	panic(fmt.Errorf("not implemented: CachedTokens - cachedTokens"))
}

// ID is the resolver for the id field.
func (r *segmentResolver) ID(ctx context.Context, obj *biz.Segment) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeRequest, ID: obj.ID}, nil
}

// ParentID is the resolver for the parentId field.
func (r *segmentResolver) ParentID(ctx context.Context, obj *biz.Segment) (*objects.GUID, error) {
	if obj.ParentID == nil {
		return nil, nil
	}

	return &objects.GUID{Type: ent.TypeRequest, ID: *obj.ParentID}, nil
}

// Model is the resolver for the model field.
func (r *segmentResolver) Model(ctx context.Context, obj *biz.Segment) (string, error) {
	panic(fmt.Errorf("not implemented: Model - model"))
}

// Children is the resolver for the children field.
func (r *segmentResolver) Children(ctx context.Context, obj *biz.Segment) ([]*biz.Segment, error) {
	panic(fmt.Errorf("not implemented: Children - children"))
}

// RequestSpans is the resolver for the requestSpans field.
func (r *segmentResolver) RequestSpans(ctx context.Context, obj *biz.Segment) ([]*biz.Span, error) {
	panic(fmt.Errorf("not implemented: RequestSpans - requestSpans"))
}

// ResponseSpans is the resolver for the responseSpans field.
func (r *segmentResolver) ResponseSpans(ctx context.Context, obj *biz.Segment) ([]*biz.Span, error) {
	panic(fmt.Errorf("not implemented: ResponseSpans - responseSpans"))
}

// Metadata is the resolver for the metadata field.
func (r *segmentResolver) Metadata(ctx context.Context, obj *biz.Segment) (*biz.RequestMetadata, error) {
	panic(fmt.Errorf("not implemented: Metadata - metadata"))
}

// StartTime is the resolver for the startTime field.
func (r *segmentResolver) StartTime(ctx context.Context, obj *biz.Segment) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: StartTime - startTime"))
}

// EndTime is the resolver for the endTime field.
func (r *segmentResolver) EndTime(ctx context.Context, obj *biz.Segment) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: EndTime - endTime"))
}

// Duration is the resolver for the duration field.
func (r *segmentResolver) Duration(ctx context.Context, obj *biz.Segment) (int, error) {
	panic(fmt.Errorf("not implemented: Duration - duration"))
}

// ID is the resolver for the id field.
func (r *spanResolver) ID(ctx context.Context, obj *biz.Span) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Type is the resolver for the type field.
func (r *spanResolver) Type(ctx context.Context, obj *biz.Span) (string, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// StartTime is the resolver for the startTime field.
func (r *spanResolver) StartTime(ctx context.Context, obj *biz.Span) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: StartTime - startTime"))
}

// EndTime is the resolver for the endTime field.
func (r *spanResolver) EndTime(ctx context.Context, obj *biz.Span) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: EndTime - endTime"))
}

// Value is the resolver for the value field.
func (r *spanResolver) Value(ctx context.Context, obj *biz.Span) (*biz.SpanValue, error) {
	panic(fmt.Errorf("not implemented: Value - value"))
}

// URL is the resolver for the url field.
func (r *spanImageURLResolver) URL(ctx context.Context, obj *biz.SpanImageURL) (*string, error) {
	panic(fmt.Errorf("not implemented: URL - url"))
}

// Text is the resolver for the text field.
func (r *spanTextResolver) Text(ctx context.Context, obj *biz.SpanText) (*string, error) {
	panic(fmt.Errorf("not implemented: Text - text"))
}

// Thinking is the resolver for the thinking field.
func (r *spanThinkingResolver) Thinking(ctx context.Context, obj *biz.SpanThinking) (*string, error) {
	panic(fmt.Errorf("not implemented: Thinking - thinking"))
}

// ToolCallID is the resolver for the toolCallID field.
func (r *spanToolResultResolver) ToolCallID(ctx context.Context, obj *biz.SpanToolResult) (*string, error) {
	panic(fmt.Errorf("not implemented: ToolCallID - toolCallID"))
}

// IsError is the resolver for the isError field.
func (r *spanToolResultResolver) IsError(ctx context.Context, obj *biz.SpanToolResult) (*bool, error) {
	panic(fmt.Errorf("not implemented: IsError - isError"))
}

// Text is the resolver for the text field.
func (r *spanToolResultResolver) Text(ctx context.Context, obj *biz.SpanToolResult) (*string, error) {
	panic(fmt.Errorf("not implemented: Text - text"))
}

// ID is the resolver for the id field.
func (r *spanToolUseResolver) ID(ctx context.Context, obj *biz.SpanToolUse) (*string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Name is the resolver for the name field.
func (r *spanToolUseResolver) Name(ctx context.Context, obj *biz.SpanToolUse) (string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Arguments is the resolver for the arguments field.
func (r *spanToolUseResolver) Arguments(ctx context.Context, obj *biz.SpanToolUse) (*string, error) {
	panic(fmt.Errorf("not implemented: Arguments - arguments"))
}

// URL is the resolver for the url field.
func (r *spanUserImageURLResolver) URL(ctx context.Context, obj *biz.SpanUserImageURL) (*string, error) {
	panic(fmt.Errorf("not implemented: URL - url"))
}

// Text is the resolver for the text field.
func (r *spanUserQueryResolver) Text(ctx context.Context, obj *biz.SpanUserQuery) (*string, error) {
	panic(fmt.Errorf("not implemented: Text - text"))
}

// UserQuery is the resolver for the userQuery field.
func (r *spanValueResolver) UserQuery(ctx context.Context, obj *biz.SpanValue) (*biz.SpanUserQuery, error) {
	panic(fmt.Errorf("not implemented: UserQuery - userQuery"))
}

// UserImageURL is the resolver for the userImageUrl field.
func (r *spanValueResolver) UserImageURL(ctx context.Context, obj *biz.SpanValue) (*biz.SpanUserImageURL, error) {
	panic(fmt.Errorf("not implemented: UserImageURL - userImageUrl"))
}

// Text is the resolver for the text field.
func (r *spanValueResolver) Text(ctx context.Context, obj *biz.SpanValue) (*biz.SpanText, error) {
	panic(fmt.Errorf("not implemented: Text - text"))
}

// Thinking is the resolver for the thinking field.
func (r *spanValueResolver) Thinking(ctx context.Context, obj *biz.SpanValue) (*biz.SpanThinking, error) {
	panic(fmt.Errorf("not implemented: Thinking - thinking"))
}

// ImageURL is the resolver for the imageUrl field.
func (r *spanValueResolver) ImageURL(ctx context.Context, obj *biz.SpanValue) (*biz.SpanImageURL, error) {
	panic(fmt.Errorf("not implemented: ImageURL - imageUrl"))
}

// ToolUse is the resolver for the toolUse field.
func (r *spanValueResolver) ToolUse(ctx context.Context, obj *biz.SpanValue) (*biz.SpanToolUse, error) {
	panic(fmt.Errorf("not implemented: ToolUse - toolUse"))
}

// ToolResult is the resolver for the toolResult field.
func (r *spanValueResolver) ToolResult(ctx context.Context, obj *biz.SpanValue) (*biz.SpanToolResult, error) {
	panic(fmt.Errorf("not implemented: ToolResult - toolResult"))
}

// SystemInstruction is the resolver for the systemInstruction field.
func (r *spanValueResolver) SystemInstruction(ctx context.Context, obj *biz.SpanValue) (*biz.SpanSystemInstruction, error) {
	panic(fmt.Errorf("not implemented: SystemInstruction - systemInstruction"))
}

// FirstUserQuery is the resolver for the firstUserQuery field.
func (r *threadResolver) FirstUserQuery(ctx context.Context, obj *ent.Thread) (*string, error) {
	return r.threadService.FirstUserQuery(ctx, obj.ID)
}

// RootSegment is the resolver for the rootSegment field.
func (r *traceResolver) RootSegment(ctx context.Context, obj *ent.Trace) (*biz.Segment, error) {
	return r.traceService.GetRootSegment(ctx, obj.ID)
}

// RawRootSegment is the resolver for the rawRootSegment field.
func (r *traceResolver) RawRootSegment(ctx context.Context, obj *ent.Trace) (objects.JSONRawMessage, error) {
	segment, err := r.traceService.GetRootSegment(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	data, err := json.Marshal(segment)
	if err != nil {
		return nil, err
	}

	return objects.JSONRawMessage(data), nil
}

// FirstUserQuery is the resolver for the firstUserQuery field.
func (r *traceResolver) FirstUserQuery(ctx context.Context, obj *ent.Trace) (*string, error) {
	return r.traceService.FirstUserQuery(ctx, obj.ID)
}

// FirstText is the resolver for the firstText field.
func (r *traceResolver) FirstText(ctx context.Context, obj *ent.Trace) (*string, error) {
	return r.traceService.FirstText(ctx, obj.ID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// RequestMetadata returns RequestMetadataResolver implementation.
func (r *Resolver) RequestMetadata() RequestMetadataResolver { return &requestMetadataResolver{r} }

// Segment returns SegmentResolver implementation.
func (r *Resolver) Segment() SegmentResolver { return &segmentResolver{r} }

// Span returns SpanResolver implementation.
func (r *Resolver) Span() SpanResolver { return &spanResolver{r} }

// SpanImageURL returns SpanImageURLResolver implementation.
func (r *Resolver) SpanImageURL() SpanImageURLResolver { return &spanImageURLResolver{r} }

// SpanText returns SpanTextResolver implementation.
func (r *Resolver) SpanText() SpanTextResolver { return &spanTextResolver{r} }

// SpanThinking returns SpanThinkingResolver implementation.
func (r *Resolver) SpanThinking() SpanThinkingResolver { return &spanThinkingResolver{r} }

// SpanToolResult returns SpanToolResultResolver implementation.
func (r *Resolver) SpanToolResult() SpanToolResultResolver { return &spanToolResultResolver{r} }

// SpanToolUse returns SpanToolUseResolver implementation.
func (r *Resolver) SpanToolUse() SpanToolUseResolver { return &spanToolUseResolver{r} }

// SpanUserImageURL returns SpanUserImageURLResolver implementation.
func (r *Resolver) SpanUserImageURL() SpanUserImageURLResolver { return &spanUserImageURLResolver{r} }

// SpanUserQuery returns SpanUserQueryResolver implementation.
func (r *Resolver) SpanUserQuery() SpanUserQueryResolver { return &spanUserQueryResolver{r} }

// SpanValue returns SpanValueResolver implementation.
func (r *Resolver) SpanValue() SpanValueResolver { return &spanValueResolver{r} }

type mutationResolver struct{ *Resolver }
type requestMetadataResolver struct{ *Resolver }
type segmentResolver struct{ *Resolver }
type spanResolver struct{ *Resolver }
type spanImageURLResolver struct{ *Resolver }
type spanTextResolver struct{ *Resolver }
type spanThinkingResolver struct{ *Resolver }
type spanToolResultResolver struct{ *Resolver }
type spanToolUseResolver struct{ *Resolver }
type spanUserImageURLResolver struct{ *Resolver }
type spanUserQueryResolver struct{ *Resolver }
type spanValueResolver struct{ *Resolver }
